# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs: 
- job: Job1
  steps:
  - script: echo Hello, world. Rohit Here!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
  - script: echo This is first step of job 2
    displayName: 'Job2-one line script'
  - script: |
      echo Line one for multi line script
      echo Line two for multi line script
    displayName: 'Job2-multi line script'    

- job: Job3
  dependsOn: Job2
  steps:
  - script: echo This is Job 3
    displayName: job3- script 